version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mcdonald
      POSTGRES_PASSWORD: litch&lemonade
      POSTGRES_DB: ace-rural-surveillance-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: